'Последовательность действий программы при добавлении теста в базу данных'
@startuml
Пользователь --> МенеджерТестов : данные теста
alt есть ли ошибки в тесте?
    МенеджерТестов --> Пользователь : ошибка
else
        МенеджерТестов --> БД : добавитьТест(данные теста : Тест)
end
БД --> МенеджерТестов : успех добавления теста
МенеджерТестов -> Пользователь : успех добавления теста
@enduml