'Последовательность действий программы при генерации тестов'
@startuml
Пользователь --> ГенераторТестов : параметры генерации
loop пока все тесты не сгенерированы
    ГенераторТестов --> БД : запрос теста
    БД --> ГенераторТестов : тест
end
ГенераторТестов --> Пользователь : сгенерированные файлы
@enduml