'Функциональная структура системы, выполненная в виде диаграммы прецедентов'
@startuml
rectangle управление_БД_тестов {
    Пользователь --> (Добавление тестов)
    Пользователь --> (Просмотр тестов)
    Пользователь --> (Редактирование тестов)
}

rectangle генерация_тестов {
    Пользователь --> (Генерация файлов тестовых вариантов)
}
@enduml