'Последовательность действий программы при просмотре тестов из базы данных'
@startuml
Пользователь --> МенеджерТестов : запрос тестов
alt запрос корректен?
    МенеджерТестов --> БД : запрос тестов
    БД --> ПросмотрщикТестов : подходящие под запрос тесты
else
    МенеджерТестов --> Пользователь : ошибка
end
@enduml