@startuml
class Starter {
    + {static} main (args : String[]) : void
}

interface IStartableCloseableFrame {
    + start() : void
    + close() : void
}

abstract class AFrame {
    - parentFrame : AFrame
    - adjustGeneralSettings() : void
    # adjustFrameSettings() {abstract} : void
    # adjustLayout() {abstract} : void
    # setListeners() {abstract} : void
}

class MainFrame {

}

class AddingFrame {
    -questionType : QuestionType
    -questionString : String
    -themes : List<String>
    -variants : List<String>
    +createQuestion() : Question
}

class ViewingFrame {
    -themes : List<String>
    +showQuestions(theme: String, count: int)
    +editQuestion(question: AQuestion)

}

class QuestionEditor {
    -description: String
    -variants : List<String>
    -answers : List<String>
    +setCurrentQuestion(question: AQuestion) : void
    +addVariant(text: String, isRight: boolean) : int
    +removeVariant(index: int) : void
    +getVariant(index: int) : String
    +answerIsRight(index: int) : int
    +getCurrentQuestion() : AQuestion
    +exec() : void
}

note right of ViewingFrame
    showQuestions показывает вопросы из
    темы theme в количестве count штук на странице.
end note

class GeneratingFrame {
    -questionCount : int
    -variantCount : int
    -themesOut : List<String>
}

class LaTeXViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

class QuestionViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

class PDFViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

Starter --> MainFrame : create >
Starter --> AddingFrame : create >
Starter --> ViewingFrame : create >
Starter --> GeneratingFrame : create >

AFrame .up.|> IStartableCloseableFrame
MainFrame -up-|> AFrame
AddingFrame -up-|> AFrame
ViewingFrame -up-|> AFrame
GeneratingFrame -up-|> AFrame

AddingFrame o-- QuestionViewingComponent
QuestionViewingComponent o-- LaTeXViewingComponent : include >

ViewingFrame *--> QuestionEditor : use >
QuestionEditor --> QuestionManager : use >

ViewingFrame "1..*" *-- QuestionViewingComponent
GeneratingFrame o-- PDFViewingComponent

@enduml

