@startuml
class Starter {
    +main {static} (args : String[]) : void
}

class MainFrame {
    -initialize() : void
    -adjustLayout() : void
    -setListeners() : void
}

class AddingFrame {
    -questionType : QuestionType
    -questionString : String
    -themes : List<String>
    -variants : List<String>
    +createQuestion() : Question
}

class ViewingFrame {
    -themes : List<String>
    +showQuestions(theme: String, count: int)
    +editQuestion(question: AQuestion)

}

class QuestionEditor {
    -description: String
    -variants : List<String>
    -answers : List<String>
    +setCurrentQuestion(question: AQuestion) : void
    +addVariant(text: String, isRight: boolean) : int
    +removeVariant(index: int) : void
    +getVariant(index: int) : String
    +answerIsRight(index: int) : int
    +getCurrentQuestion() : AQuestion
    +exec() : void
}
note right of ViewingFrame
    showQuestions показывает вопросы из
    темы theme в количестве count штук на странице.
end note

class GeneratingFrame {
    -questionCount : int
    -variantCount : int
    -themesOut : List<String>
}


class LaTeXViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

class QuestionViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

class PDFViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

AddingFrame o-- QuestionViewingComponent
QuestionViewingComponent o-- LaTeXViewingComponent : include >

ViewingFrame "1..*" *-- QuestionViewingComponent
GeneratingFrame o-- PDFViewingComponent

MainFrame --> AddingFrame : create >
MainFrame --> ViewingFrame : create >
MainFrame --> GeneratingFrame : create >

ViewingFrame *--> QuestionEditor : use >
QuestionEditor --> QuestionManager : use >

Starter ..> MainFrame

@enduml

