@startuml

class Question {
    - id : int
    - category : String
    - description : String
    - answers : Collection<Answer>
}

class Answer {
        - id : int
        - value : String
        - correct : boolean
        - question : Question
}

Question "1" <--> "0..*" Answer

note bottom of Question
    Предполагается, что ТО, что будет показывать
    вопрос, будет смотреть на количество вариантов ответа.
    Если их больше 1, то составляется вопрос с вариантами:
    ==
    Здесь будет записан текст вопроса.
    а) вариант ответа 1
    б) вариант ответа 2
    ==
    Если их нет, составляется вопрос с полем для ввода ответа.
    ==
    Здесь будет записан текст вопроса.
    Ответ: _____________
    ==
    Если вариант ответа один, то это очень странный вопрос. Наверное,
    следует генерить ошибку.
end note

@enduml