@startuml
!include questions.puml

class QuestionManager<<(S,#FF7700) Singleton>> {
    +addQuestion(question : Question, themes : List<String>) : boolean
    -checkQuestion(question : Question) : boolean
    -questions : List<Question>
    -dbconnector : DBConnector
    +addQuestion(q: Question) : void
    +removeQuestion(q: Question) : void
    +getQuestions(theme: String) : List<Question>
    +getThemes(question: Question) : List<String>
    +load()
    +save()
}

QuestionManager *--> "*" Question

@enduml