'Общая диаграмма классов генератора тестов'
@startuml
!include questionManagement.puml
!include frames.puml
!include generation.puml



AddingFrame --> QuestionManager : use >

AddingFrame ..> Question : create >
QuestionManager ..> DBFacade
ViewingFrame --> QuestionManager : use >

@enduml
