'Последовательность действий программы при добавлении теста в базу данных'
@startuml
actor User
User --> MainForm : initialize()
activate MainForm
MainForm --> MainForm : changeCurrentForm()
activate AddingForm
User --> AddingForm : some data
AddingForm --> AddingForm : formQuestion()
AddingForm --> QuestionAdder : checkQuestion(question : Question)
activate QuestionAdder
QuestionAdder --> AddingForm : isQuestionCorrect : boolean
alt isQuestionCorrect == true
    QuestionAdder --> DBConnector : addQuestion(question : Question, themes : List<Theme>)
    DBConnector --> DBConnector : addQuestion(question : Question, themes : List<Theme>)
    DBConnector --> QuestionAdder : isQuestionAdded : boolean
    QuestionAdder --> AddingForm : isQuestionAdded : boolean
end
@enduml