'Последовательность действий программы при редактировании теста в базе данных'
@startuml
Пользователь --> МенеджерТестов : номер теста
alt есть ли такой тест в БД?
    МенеджерТестов --> БД : запрос данных теста
    БД --> РедакторТестов : данные теста
    activate РедакторТестов
    РедакторТестов --> БД : измененные данные теста
    deactivate РедакторТестов
    БД --> МенеджерТестов : успех добавления теста
    МенеджерТестов -> Пользователь : успех добавления теста
else
    МенеджерТестов --> Пользователь : ошибка
end
@enduml