@startuml
interface Question{
+{abstract}getDescription() : string
+{abstract}answerIsRight(_answer: Object) : boolean
}


abstract AQuestion{
-description_ : string
}

abstract VariantQuestion{
-answers_ : vector<Object>
+getVariants() : vector<Object>
+{abstract}getRightAnswer() :  vector<Object>
}

class CheckBoxQuestion{
-right_answers_ : vector<Object>
+answerIsRight(_answer: Object) : boolean
}

class RadioQuestion{
-right_answer_ : string
+answerIsRight(_answer: Object) : boolean
}

class TextQuestion{
-text: string
+answerIsRight(_answer: Object) : boolean
}
class ValueQuestion{
-value_: double
+answerIsRight(_answer: Object) : boolean
}

AQuestion ..|> Question
VariantQuestion --|> AQuestion
CheckBoxQuestion --|> VariantQuestion
RadioQuestion --|> VariantQuestion
TextQuestion --|> AQuestion
ValueQuestion --|> AQuestion

@enduml