@startuml
abstract Question{
    -description : String
    -themes: List<String>
    +getDescription() : string
    +{abstract}checkAnswers(answers: List<String>) : boolean
}

class VariantQuestion{
    -answers : List<String>
    +getVariants() : List<String>
    +getRightAnswers() :  List<String>
    +checkAnswers(answers: List<String>) : boolean
}

class TextQuestion{
    -text: String
    +answerIsRight(answer: String) : boolean
    +checkAnswers(answers: List<String>) : boolean
}


VariantQuestion -up--|> Question
TextQuestion -up--|> Question


@enduml