@startuml
!include questions.puml


class QuestionManager{
-questions : List<Question>
-dbconnector : DBConnector
+addQuestion(q: Question)
+getQuestions(theme: String) : List<Question>
+getThemes(question: Question) : List<String>
+load()
+save()
}

QuestionManager *--> "*" Question



@enduml