@startuml
!include questions.puml

interface Theme{
+{abstract}getDescription() : string
}

class QuestionManager{
-keepers : List<QuestionKeeper>
+addQuestion(q: Question, themes: List<Themes>)
+getQuestions(theme: Theme) : List<Question>
+getThemes(question: Question) : List<Themes>
}

class QuestionKeeper{
-question: Question
-themes: List<Theme>
+addQuestionToTheme(theme: Theme) : void
}

QuestionKeeper "1" *--> "1" Question
QuestionKeeper "1" o--> "*" Theme
QuestionManager "1" *--> "*" QuestionKeeper
QuestionManager ..> QuestionKeeper : create
@enduml