'Общая диаграмма классов генератора тестов'
@startuml
'!include themes.puml
class DBConnector <<(S,#FF7700) Singletone>> {
    +getInstance() : DBConnector
    ..
    +getQuestionByID(id : long) : Question
    +findQuestionsByName(query : String) : List<Question>
    +findQuestionsByContent(query : String) : List<Question>
    +getQuestionsByTheme(themes : List<Theme>) : List<Question>
    +addQuestion(question : Question, themes : List<Theme>) : boolean
}

class QuestionGenerator {
    +getRandomQuestionsInTheme(themes : List<String>, quantity : int, variants : int) : List<Question>
}

class MainForm {
    -currentFrame : javax.swing.JFrame
    +main {static} (args : String[]) : void
    +changeCurrentFrame(frame) : boolean
    -initialize() : void
}

class AddingForm {
    -questionType : QuestionType
    -questionString : String
    -question : Question
    -themes : List<String>
    -formQuestion() : Question
}

class ViewingForm {
    -theme : Theme
    -amount : int
}

class GeneratingForm {
    -questionCount : int
    -variantCount : int
    -themesOut : List<String>
}

class QuestionAdder {
    +addQuestion(question : Question, themes : List<Theme>) : boolean
    -checkQuestion(question : Question) : boolean
}

class LaTeXViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

class QuestionViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

class PDFGenerator {
    +generatePDF(questionList : List<Questions>) : PDFFile
}

class PDFViewingComponent {
    +paintComponent(graphics : java.awt.Graphics, string : String)
}

QuestionGenerator --> DBConnector

MainForm  o--> AddingForm : create >
AddingForm --> QuestionAdder : use >
QuestionAdder --> DBConnector : use >

AddingForm o-- QuestionViewingComponent
QuestionViewingComponent o-- LaTeXViewingComponent : include >

MainForm o--> ViewingForm : create >
ViewingForm "1..*" *-- QuestionViewingComponent

MainForm o--> GeneratingForm : create >
GeneratingForm --> QuestionGenerator : use >
GeneratingForm --> PDFGenerator : use >
GeneratingForm o-- PDFViewingComponent
@enduml
